name: Auto-Update VPN Sub

on:
  schedule:
    - cron: '0 */3 * * *' # Запускать каждые 3 часа
  workflow_dispatch: # Позволяет запустить экшен вручную

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Скачиваем код (Checkout)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Настраиваем Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Устанавливаем зависимости
        run: npm install

      - name: Запускаем скрипт-парсер
        env:
          TG_CHANNEL_URL: ${{ secrets.TG_CHANNEL_URL }}
          TG_HALYAVA_URL: ${{ secrets.TG_HALYAVA_URL }}
        run: node index.js

      - name: Отправляем файлы на хостинг
        env:
          SOURCECRAFT_TOKEN: ${{ secrets.SOURCECRAFT_TOKEN }}
          SOURCECRAFT_REPO: ${{ secrets.SOURCECRAFT_REPO }}
        run: |
          # Используем правильный домен для git (git.sourcecraft.dev) и username (anyname) согласно документации

          # 1. Клонируем репозиторий с хостинга во временную папку remote_repo
          git clone https://anyname:${SOURCECRAFT_TOKEN}@git.sourcecraft.dev/${SOURCECRAFT_REPO}.git remote_repo

          # 2. Перемещаем оба свежесгенерированных файла в эту папку (перезаписываем старые)
          mv base64_player_id_game.txt remote_repo/
          mv base64_player_id_game2.txt remote_repo/

          # 3. Переходим в папку, коммитим и пушим обратно на хостинг
          cd remote_repo
          git config --local user.email "action@github.com"
          git config --local user.name "Auto Updater"
          git add base64_player_id_game.txt base64_player_id_game2.txt

          # Коммитим и пушим, только если файлы обновились
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update subscription" && git push)
